#!/bin/bash
set -x
echo "SCRIPT STARTED"

WORK_DIR="/tmp/work/1667730m"

# Install Apache
puppet resource package apache2 ensure=present;

# Start and enable Apache
puppet resource service apache2 ensure=running enable=true;


# Ensure parent directory exists
puppet resource file /tmp/work ensure=directory;

# Remove previous work dir if exists
puppet resource file $WORK_DIR ensure=absent force=true;

# Recreate work directory
puppet resource file $WORK_DIR ensure=directory;

# Install git if not present
puppet resource package git ensure=present;

# Move into work directory
cd $WORK_DIR;


# Clone repository
git clone https://github.com/1667730M/app-1667730m-repo.git;

# Deploy index.html
cp -p $WORK_DIR/app-1667730m-repo/new_1667730m_index.html /var/www/html/index.html;

echo "Application deployed successfully inside container"